#!/usr/bin/env python3
"""Convert the Cleere logo to an Inkplate 10 3-bit grayscale C header.

Output format matches Inkplate::drawBitmap3Bit():
  - row stride = ceil(W/2) bytes, 2 pixels per byte (high nibble = even x)
  - stored nibble = level<<1, where level in 0..7 (0=black, 7=white)
"""
import sys
from PIL import Image, ImageOps

import os
_HERE = os.path.dirname(os.path.abspath(__file__))
SRC = sys.argv[1] if len(sys.argv) > 1 else os.path.join(_HERE, "logo_src.jpg")
OUT = sys.argv[2] if len(sys.argv) > 2 else r"C:\Users\gravi\Documents\rust\soldered_clock\src\logo.h"
W, H = 1200, 600  # full panel width, logo is 2:1

img = Image.open(SRC).convert("RGB")
# White background flatten (in case of alpha already handled by RGB)
img = img.convert("L")                 # luminance grayscale
img = ImageOps.autocontrast(img, cutoff=1)
img = img.resize((W, H), Image.LANCZOS)

px = list(img.getdata())               # 0..255, row-major

# Floyd-Steinberg dithering to 8 levels for smooth gear gradient.
buf = [float(p) for p in px]
def at(x, y):
    return buf[y * W + x]
def setp(x, y, v):
    buf[y * W + x] = v

for y in range(H):
    for x in range(W):
        old = at(x, y)
        lvl = round(old / 255 * 7)
        new = lvl / 7 * 255
        setp(x, y, new)
        err = old - new
        if x + 1 < W:
            setp(x + 1, y, at(x + 1, y) + err * 7 / 16)
        if y + 1 < H:
            if x > 0:
                setp(x - 1, y + 1, at(x - 1, y + 1) + err * 3 / 16)
            setp(x, y + 1, at(x, y + 1) + err * 5 / 16)
            if x + 1 < W:
                setp(x + 1, y + 1, at(x + 1, y + 1) + err * 1 / 16)

def level(x, y):
    return max(0, min(7, round(buf[y * W + x] / 255 * 7)))

stride = (W + 1) // 2
data = bytearray()
for y in range(H):
    for j in range(stride):
        xe = j * 2
        xo = xe + 1
        ne = level(xe, y) << 1
        no = (level(xo, y) << 1) if xo < W else 0
        data.append((ne << 4) | no)

with open(OUT, "w") as f:
    f.write("#pragma once\n")
    f.write("// Auto-generated by tools/gen_logo.py - Cleere Auto Services logo\n")
    f.write("// Inkplate 10 3-bit grayscale, draw with display.drawBitmap3Bit(x, y, logo3bit, LOGO_W, LOGO_H)\n")
    f.write(f"#define LOGO_W {W}\n#define LOGO_H {H}\n")
    f.write("const unsigned char logo3bit[] = {\n")
    for i, b in enumerate(data):
        f.write(f"0x{b:02x},")
        if (i + 1) % 24 == 0:
            f.write("\n")
    f.write("\n};\n")

print(f"Wrote {OUT}: {len(data)} bytes ({W}x{H}, stride {stride})")
